/**
 * site-search.js
 * Smart Component — Pagefind-powered site-wide search with dropdown results.
 *
 * CSS is auto-injected by deriving the path from this script's own src URL,
 * so no separate <link> tag is needed in HTML pages.
 *
 * Requires: components-init.js loaded first (window.ComponentLoader)
 * Requires: Pagefind index at /pagefind/pagefind.js (generated by `npm run build`)
 */

// ── CSS auto-injection ────────────────────────────────────────────────────────
(function injectCSS() {
  if (document.querySelector("link[data-site-search-css]")) return;
  const scriptSrc = document.currentScript?.src || "";
  if (!scriptSrc) return;
  const cssHref = scriptSrc.replace(/site-search\.js(\?.*)?$/, "site-search.css");
  const link = document.createElement("link");
  link.rel = "stylesheet";
  link.href = cssHref;
  link.setAttribute("data-site-search-css", "");
  document.head.appendChild(link);
})();

// ── Component registration ────────────────────────────────────────────────────
window.ComponentLoader.registerComponent("site-search", (root) => {
  if (root.__initialized) return;
  root.__initialized = true;

  // ── State ──────────────────────────────────────────────────────────────────
  const state = {
    query: "",
    results: [],
    focusedIndex: -1,
    isOpen: false,
    pagefind: null,
    loading: false,
  };

  // ── Refs ───────────────────────────────────────────────────────────────────
  const input = root.querySelector('input[type="text"]');
  if (!input) return;

  // Build dropdown element and append to root
  const dropdown = document.createElement("div");
  dropdown.className = "ss-dropdown";
  root.appendChild(dropdown);

  // ── Pagefind lazy loader ───────────────────────────────────────────────────
  const loadPagefind = async () => {
    if (state.pagefind) return;
    try {
      // Pagefind index is always at the site root regardless of page depth
      state.pagefind = await import("/pagefind/pagefind.js");
      await state.pagefind.init();
    } catch (err) {
      // In development (before `npm run build`), this will fail silently
      console.warn("[SiteSearch] Pagefind not ready — run `npm run build` first.", err.message);
    }
  };

  // ── Helpers ────────────────────────────────────────────────────────────────
  const escapeHtml = (str) =>
    String(str ?? "")
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");

  const openDropdown = () => {
    state.isOpen = true;
    dropdown.classList.add("is-open");
  };

  const closeDropdown = () => {
    state.isOpen = false;
    state.focusedIndex = -1;
    dropdown.classList.remove("is-open");
  };

  const setFocus = (index) => {
    state.focusedIndex = index;
    const items = dropdown.querySelectorAll(".ss-result");
    items.forEach((el, i) => el.classList.toggle("is-focused", i === index));
    if (index >= 0 && items[index]) {
      items[index].scrollIntoView({ block: "nearest" });
    }
  };

  // ── Rendering ──────────────────────────────────────────────────────────────
  const renderStatus = (message) => {
    dropdown.innerHTML = `<div class="ss-status">${message}</div>`;
    openDropdown();
  };

  const renderResults = () => {
    if (!state.results.length) {
      renderStatus(`No results for <strong>${escapeHtml(state.query)}</strong>`);
      return;
    }

    // Build result links — note: r.excerpt already contains safe HTML with <mark> highlights
    const items = state.results
      .map(
        (r, i) => `
      <a href="${r.url}" class="ss-result${i === state.focusedIndex ? " is-focused" : ""}">
        ${r.meta?.section ? `<span class="ss-result__section">${escapeHtml(r.meta.section)}</span>` : ""}
        <span class="ss-result__title">${escapeHtml(r.meta?.title || r.url)}</span>
        <span class="ss-result__excerpt">${r.excerpt}</span>
      </a>`
      )
      .join("");

    dropdown.innerHTML = `<div class="ss-results">${items}</div>`;
    openDropdown();
  };

  // ── Search ─────────────────────────────────────────────────────────────────
  const search = async (query) => {
    if (!state.pagefind) {
      await loadPagefind();
      if (!state.pagefind) return;
    }
    if (!query.trim()) {
      closeDropdown();
      return;
    }
    renderStatus("Searching…");
    try {
      const result = await state.pagefind.search(query);
      state.results = await Promise.all(result.results.slice(0, 6).map((r) => r.data()));
      state.focusedIndex = -1;
      renderResults();
    } catch (err) {
      console.error("[SiteSearch] Search error:", err);
      closeDropdown();
    }
  };

  // ── Debounce ───────────────────────────────────────────────────────────────
  let debounceTimer = null;
  const debouncedSearch = (query) => {
    clearTimeout(debounceTimer);
    if (!query.trim()) {
      closeDropdown();
      return;
    }
    debounceTimer = setTimeout(() => search(query), 300);
  };

  // ── Event listeners ────────────────────────────────────────────────────────
  // Pre-load pagefind on first focus (warm up the WASM)
  input.addEventListener("focus", loadPagefind, { once: true });

  input.addEventListener("input", (e) => {
    state.query = e.target.value;
    debouncedSearch(state.query);
  });

  input.addEventListener("keydown", (e) => {
    if (!state.isOpen) return;
    const items = dropdown.querySelectorAll(".ss-result");

    switch (e.key) {
      case "ArrowDown":
        e.preventDefault();
        setFocus(Math.min(state.focusedIndex + 1, items.length - 1));
        break;
      case "ArrowUp":
        e.preventDefault();
        setFocus(Math.max(state.focusedIndex - 1, -1));
        break;
      case "Enter":
        e.preventDefault();
        if (state.focusedIndex >= 0 && items[state.focusedIndex]) {
          items[state.focusedIndex].click();
        } else if (state.results[0]) {
          window.location.href = state.results[0].url;
        }
        break;
      case "Escape":
        closeDropdown();
        input.blur();
        break;
    }
  });

  // Close dropdown when clicking outside the component root
  const onOutsideClick = (e) => {
    if (!root.contains(e.target)) closeDropdown();
  };
  document.addEventListener("click", onOutsideClick);

  console.log("[Component] Site Search initialized.");
});
